=== erwinel/FsInfoCat/src/FsInfoCat.Test/Resources/UrlHelperTest.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="CaptureType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="Success" type="xs:boolean" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="GroupType">
        <xs:complexContent>
            <xs:extension base="CaptureType">
                <xs:attribute name="Name" type="xs:string" use="required" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="MatchType">
        <xs:sequence minOccurs="0">
            <xs:element maxOccurs="unbounded" name="Group" type="GroupType" />
        </xs:sequence>
        <xs:attribute name="Success" type="xs:boolean" use="required" />
    </xs:complexType>
    <xs:complexType name="OSType">
        <xs:sequence>
            <xs:element name="FsPathRegex" type="MatchType" />
            <xs:element name="FsPathPattern" type="CaptureType" />
            <xs:element name="FormatGuess" type="MatchType" />
            <xs:element name="FileUriStrict" type="MatchType" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AuthorityCaseInsensitiveEqualsType">
        <xs:attribute name="Description" type="xs:string" use="required" />
        <xs:attribute name="CompareTo" type="xs:string" use="required" />
        <xs:attribute name="Returns" type="xs:boolean" use="required" />
    </xs:complexType>
    <xs:complexType name="TestDataType">
        <xs:sequence>
            <xs:element name="Windows" type="OSType" />
            <xs:element name="Linux"  type="OSType" />
            <xs:element name="AuthorityCaseInsensitiveEquals" type="AuthorityCaseInsensitiveEqualsType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="Value" type="xs:string" use="required" />
        <xs:attribute name="Description" type="xs:string" use="required" />
        <xs:attribute name="Base64" type="xs:boolean" use="optional" />
    </xs:complexType>
    <xs:element name="UrlHelperTest">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="TestData" type="TestDataType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== erwinel/FsInfoCat/src/FsInfoCat.Test/Resources/UrlHelperTest.xml
<UrlHelperTest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./UrlHelperTest.xsd">
    <TestData Value="" Description="Empty String">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true"></Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true"></Group>
            </FileUriStrict>
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true"></Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true"></Group>
            </FileUriStrict>
        </Linux>
        <AuthorityCaseInsensitiveEquals CompareTo="" Returns="true" Description="Empty URI" />
        <AuthorityCaseInsensitiveEquals CompareTo=" " Returns="false" Description="White space" />
    </TestData>
    <TestData Value="^_`jkq{}" Description="Relative single segment path">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">^_`jkq{}</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">^_`jkq{}</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Linux>
    </TestData>
    <TestData Value="%5E_jkq%7B%7D" Description="Relative single segment URI">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">%5E_jkq%7B%7D</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">%5E_jkq%7B%7D</Group>
            </FileUriStrict>
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">%5E_jkq%7B%7D</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">%5E_jkq%7B%7D</Group>
            </FileUriStrict>
        </Linux>
    </TestData>
    <TestData Value="!$'+,@BKQY\" Description="Relative single segment Windows path">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">!$'+,@BKQY\</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">!$'+,@BKQY\</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Linux>
    </TestData>
    <TestData Value="!$'+,@BKQY/" Description="Relative single segment Linux path">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">!$'+,@BKQY/</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">!$'+,@BKQY/</Group>
            </FileUriStrict>
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">!$'+,@BKQY/</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">!$'+,@BKQY/</Group>
            </FileUriStrict>
        </Linux>
    </TestData>
    <TestData Value="AppData\Local\Temp" Description="Relative Nested Windows path">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">AppData\Local\Temp</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">AppData\Local\Temp</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Linux>
    </TestData>
    <TestData Value="mnt/cdrom files" Description="Relative Nested Linux path">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">mnt/cdrom files</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">mnt/cdrom files</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="false" />
        </Linux>
    </TestData>
    <TestData Value="mnt/cdrom%20files" Description="Relative Nested URI">
        <Windows>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">mnt/cdrom%20files</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">mnt/cdrom%20files</Group>
            </FileUriStrict>
        </Windows>
        <Linux>
            <FsPathRegex Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">mnt/cdrom%20files</Group>
            </FsPathRegex>
            <FsPathPattern Success="false" />
            <FormatGuess Success="false" />
            <FileUriStrict Success="true">
                <Group Name="a" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">mnt/cdrom%20files</Group>
            </FileUriStrict>
        </Linux>
    </TestData>

    <TestData Value="file:///z:/Index%233&amp;4" Description="Windows Drive URL">
        <Windows>
            <FsPathRegex Success="false" />
            <FsPathPattern Success="false" />
            <FormatGuess Success="true">
                <Group Name="f" Success="true">file:///z:/Index%233&amp;4</Group>
                <Group Name="u" Success="false" />
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">/z:/Index%233&amp;4</Group>
                <Group Name="x" Success="false" />
            </FormatGuess>
            <FileUriStrict Success="true">
                <Group Name="a" Success="true">file:///z:/Index%233&amp;4</Group>
                <Group Name="h" Success="false" />
                <Group Name="p" Success="true">/z:/Index%233&amp;4</Group>
            </FileUriStrict>
